
server:
  port: ${PORT:8090}
  
spring:
  application:
    name: zuul-server
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
zuul:
  routes:
    product:
      service-id: product-service
      path: /api/product/**
      
    item:
      service-id: item-service
      path: /api/item/**
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon: 
  ReadTimeout: 3000
  ConnectTimeout: 10000
      
logging:
  file: logs/${spring.application.name:zuul-server}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.evertcode.app: 'DEBUG' 