server:
  port: ${PORT:8761}
  
spring:
  application:
    name: eureka-server
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
logging:
  file: logs/${spring.application.name:eureka-server}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.evertcode.app: 'DEBUG' 
